services:
  backend:
    build:
      context: ./yihen-drama
      dockerfile: Dockerfile
      args:
        MAVEN_IMAGE: docker.1ms.run/library/maven:3.9.9-eclipse-temurin-17
        JRE_IMAGE: docker.1ms.run/library/eclipse-temurin:17-jre
    container_name: yihen-backend
    restart: unless-stopped
#    depends_on:
#      mysql:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#      mq:
#        condition: service_healthy
#      minio:
#        condition: service_started
#      es:
#        condition: service_healthy
#      qdrant:
#        condition: service_started
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/YihenDrama?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yihen0214
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: mq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: yihen
      SPRING_RABBITMQ_PASSWORD: yihen0214
      SPRING_ELASTICSEARCH_URIS: http://es:9200
      MINIO_END_POINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6334
      QDRANT_COLLECTION_NAME: novel_content
      QDRANT_DIMENSION: 384
      QDRANT_MAX_SEGMENTSIZE_IN_TOKENS: 300
      QDRANT_MAX_OVERLAP_SIZE_IN_TOKENS: 30
      QDRANT_MAX_RESULT: 5
      QDRANT_MIN_SCORE: 0.8
    ports:
      - "8080:8080"
